### ISSUE TITLE
On side hierarchy side bar once an AUH is selected red it can be be reselected

### ISSUE THREAD

**Issue by weherr** [ECS193EnergyDashboard/EnergyDashboard#44]
On the left most side bar click on AHU 1 so all its children show on the data table. The AHU 1 should be highlighted red. Then clear everything from the table using the quick clear on the second side bar. Now try to put back AHU 1 and it won't let you, you have to add click somewhere else on the sidebar to get it to not be red then re-add it.

**Comment by ChrisAranda** [comment]
Fixed with 75967543c64c8d9f0c5f9144bf95d54faf93451b on branch SiteRedesign
